/* Automatically generated by po2tbl.sed from pybliographer.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"This is %s, version %s", 2},
  {"%s: error: can't open file `%s'", 3},
  {"For help, run %s and type `help' at the prompt", 4},
  {"\
Useful commands:\n\
\thelp     to get some help\n\
\tquit     to quit\n", 5},
  {"entry has no key `%s'", 6},
  {"error: field `%s' appears more than once in the definition of `%s'", 7},
  {"no update method defined", 8},
  {"database `%s' is unknown in this Reference", 9},
  {"can't update a database of type Reference ()", 10},
  {"key `%s' is malformed", 11},
  {"%s:%d: key `%s' already defined", 12},
  {"in entry %s: nested crossrefs", 13},
  {"Native editing of field `%s'", 14},
  {"Edit the field in its Native format", 15},
  {"Drag an Entry to define a Cross-Reference", 16},
  {"Remove the current Cross-Reference", 17},
  {"Add Extra Field", 18},
  {"Cross-Reference `%s' is unexistent in the database", 19},
  {"Mandatory", 20},
  {"Optional", 21},
  {"Extra", 22},
  {"Invalid field name `%s'", 23},
  {"Key `%s' already defined", 24},
  {"Invalid identifier `%s'", 25},
  {"Identifier `%s' already exists", 26},
  {"File", 27},
  {"Bibliography type:", 28},
  {"Format", 29},
  {"Formatting Style:", 30},
  {"Output type:", 31},
  {"Submit a Bug Report", 32},
  {"Welcome to Pybliographic", 33},
  {"New...", 34},
  {"Edit...", 35},
  {"Delete", 36},
  {"Modified database `%s' [%s, %d]", 37},
  {"Database `%s' [%s, %d]", 38},
  {"New file", 39},
  {"Database is modified.\n", 40},
  {"Discard changes ?", 41},
  {"Open", 42},
  {"Quit without saving ?", 43},
  {"can't save file: %s", 44},
  {"Save As", 45},
  {"\
File `%s' exists.\n\
Overwrite it ?", 46},
  {"\
Can't save file:\n\
%s", 47},
  {"Not yet implemented...", 48},
  {"\
Please, create a new database first.\n\
Use File/New for example", 49},
  {"editing is disabled in this database", 50},
  {"edition is disabled in this database", 51},
  {"\
Can't connect to LyX:\n\
%s", 52},
  {"Really remove entry %s ?", 53},
  {"\
Please install bug-buddy\n\
to use this feature", 54},
  {"This program is copyrighted under the GNU GPL", 55},
  {"Gnome interface to the Pybliographer system.", 56},
  {"\
Submit a bug report\n\
 using bug-buddy", 57},
  {"Pybliographer Home Page", 58},
  {"Please open a database first", 59},
  {"Bibliography", 60},
  {"Search", 61},
  {"Field", 62},
  {"Pattern", 63},
  {"Simple Search", 64},
  {"Search command:", 65},
  {"Expert Search", 66},
  {"Full database", 67},
  {"Ready to search !", 68},
  {"internal error during evaluation", 69},
  {"\
while compiling %s\n\
error: %s", 70},
  {"found %d matches", 71},
  {"%d matches in this node", 72},
  {"\
The following errors occured:\n\
\n", 73},
  {"warning: can't import %s: %s", 74},
};

int _msg_tbl_length = 74;
