/* Automatically generated by po2tbl.sed from pybliographer.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"warning: can't import %s: %s", 2},
  {"value of `%s' should be of type %s", 3},
  {"String", 4},
  {"Boolean", 5},
  {"Integer", 6},
  {"Integer under %d", 7},
  {"Integer over %d", 8},
  {"Integer between %d and %d", 9},
  {"Element in `%s'", 10},
  {"Tuple (%s)", 11},
  {"List (%s)", 12},
  {"Dictionnary (%s, %s)", 13},
  {"Illegal year value", 14},
  {"Illegal month value", 15},
  {"Illegal day value", 16},
  {"in %s", 17},
  {"no input pipe `%s'", 18},
  {"no output pipe `%s'", 19},
  {"method `%s' provides no opener", 20},
  {"File `%s' does not exist", 21},
  {"don't know how to open `%s'", 22},
  {"method `%s' provides no iterator", 23},
  {"key `%s' is malformed", 24},
  {"%s:%d: key `%s' already defined", 25},
  {"Format entries", 26},
  {"Bibliography style:", 27},
  {"Select style", 28},
  {"Output format:", 29},
  {"Output File:", 30},
  {"Select output file", 31},
  {"Day", 32},
  {"Month", 33},
  {"Year", 34},
  {"Invalid day field in date", 35},
  {"Invalid month field in date", 36},
  {"Invalid year field in date", 37},
  {"Entry type", 38},
  {"Key", 39},
  {"Create Field", 40},
  {"Mandatory", 41},
  {"Optional", 42},
  {"Extra", 43},
  {"New text", 44},
  {"Invalid key format", 45},
  {"Key `%s' already exists", 46},
  {"Error in native string parsing", 47},
  {"Native Editing", 48},
  {"Standard Editing", 49},
  {"File", 50},
  {"Bibliography type:", 51},
  {"Add...", 52},
  {"Edit...", 53},
  {"Delete", 54},
  {"Search", 55},
  {"Field", 56},
  {"Pattern", 57},
  {"Simple Search", 58},
  {"Search command:", 59},
  {"Expert Search", 60},
  {"Full database", 61},
  {"internal error during evaluation", 62},
  {"\
while compiling %s\n\
error: %s", 63},
  {"Select sort criterions", 64},
  {"In use", 65},
  {"Sort criterions", 66},
  {"[Entry Type]", 67},
  {"[Key Value]", 68},
  {"Reorder", 69},
  {"Unselect all", 70},
  {"Yes", 71},
  {"\
The following errors occured:\n\
\n", 72},
  {"New", 73},
  {"Merge...", 74},
  {"Previous Documents", 75},
  {"About...", 76},
  {"Submit a Bug Report", 77},
  {"Sort...", 78},
  {"Cite", 79},
  {"Format...", 80},
  {"Edit", 81},
  {"Settings", 82},
  {"Help", 83},
  {"Open", 84},
  {"Save", 85},
  {"Find", 86},
  {"Close", 87},
  {"\
can't open file `%s' for writing:\n\
%s", 88},
  {"New database", 89},
  {"[no entry]", 90},
  {"[1 entry]", 91},
  {"[%d entries]", 92},
  {"[%d/1 entry]", 93},
  {"[%d/%d entries]", 94},
  {"[modified]", 95},
  {"\
The database has been modified.\n\
Discard changes ?", 96},
  {"Merge file", 97},
  {"Open error", 98},
  {"Merge status", 99},
  {"Open file", 100},
  {"\
Unable to save `%s':\n\
%s", 101},
  {"\
An internal error occured during saving\n\
Try to Save As...", 102},
  {"\
The file `%s' already exists.\n\
Overwrite it ?", 103},
  {"\
During opening:\n\
%s", 104},
  {"\
An entry called `%s' already exists.\n\
Rename and add it anyway ?", 105},
  {"Really remove all the entries ?", 106},
  {"Really edit %d entries ?", 107},
  {"Remove all the %d entries ?", 108},
  {"Remove entry `%s' ?", 109},
  {"\
Can't connect to LyX:\n\
%s", 110},
  {"\
Please install bug-buddy\n\
to use this feature", 111},
  {"This program is copyrighted under the GNU GPL", 112},
  {"Gnome interface to the Pybliographer system.", 113},
  {"Pybliographer Home Page", 114},
  {"This is %s, version %s", 115},
  {"This is free software with ABSOLUTELY NO WARRANTY.", 116},
  {"For details, type `warranty'.", 117},
  {"%s: error: can't open file `%s'", 118},
  {"For help, run %s and type `help' at the prompt", 119},
  {"\
Useful commands:\n\
\thelp     to get some help\n\
\tquit     to quit\n", 120},
  {"usage: pybcompact <latexfile> <bibtexfiles...>", 121},
  {"pybcompact: error: %s\n", 122},
  {"no entry", 123},
  {"can't find the following entries: %s", 124},
  {"usage: pybconvert <source>..<target> <input> [output]", 125},
  {"pybconvert: bad conversion format", 126},
  {"usage: pybformat [bibtexfiles...]\n", 127},
  {"pybformat: error: %s\n", 128},
  {"pybformat: warning: %s\n", 129},
  {"can't find style `%s'", 130},
  {"usage: pybtex <latexfile> [bibtexfiles...]", 131},
  {"pybtex: error: %s\n", 132},
  {"pybtex: warning: the following keys were not resolved", 133},
  {"no style defined", 134},
};

int _msg_tbl_length = 134;
