# Pybliographer Italian Translation.
# Copyright (C) 1999, 2000 Free Software Foundation, Inc.
# Yuri Bongiorno <yurix@tiscalinet.it>, 1999, 2000.
#
msgid ""
msgstr ""
"Project-Id-Version: pybliographer-1.0.7\n"
"POT-Creation-Date: 2000-12-27 18:19+ZONE\n"
"PO-Revision-Date: 2000-12-27 21:40+0100\n"
"Last-Translator: Yuri Bongiorno <yurix@tiscalinet.it>\n"
"Language-Team: Italian <it@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=iso-8859-1\n"
"Content-Transfer-Encoding: 8bit\n"

#: .././Pyblio/Autoload.py:57
msgid "warning: can't import %s: %s"
msgstr "attenzione: impossibile importare %s: %s"

#: .././Pyblio/Config.py:53
msgid "value of `%s' should be of type %s"
msgstr "il valore di `%s' dovrebbe essere di tipo %s"

#: .././Pyblio/Config.py:196
msgid "String"
msgstr "Stringa"

#: .././Pyblio/Config.py:205
msgid "Boolean"
msgstr "Booleano"

#: .././Pyblio/Config.py:224
msgid "Integer"
msgstr "Intero"

#: .././Pyblio/Config.py:226
msgid "Integer under %d"
msgstr "Intero minore di %d"

#: .././Pyblio/Config.py:228
msgid "Integer over %d"
msgstr "Intero maggiore di %d"

#: .././Pyblio/Config.py:230
msgid "Integer between %d and %d"
msgstr "Intero compreso tra %d e %d"

#: .././Pyblio/Config.py:242
msgid "Element in `%s'"
msgstr "Elemento in `%s'"

#: .././Pyblio/Config.py:262
msgid "Tuple (%s)"
msgstr "Tupla (%s)"

#: .././Pyblio/Config.py:283
msgid "List (%s)"
msgstr "Lista (%s)"

#: .././Pyblio/Config.py:308
msgid "Dictionary (%s, %s)"
msgstr "Dizionario (%s, %s)"

#: .././Pyblio/Fields.py:265
msgid "Illegal year value"
msgstr "Valore dell'anno non lecito"

#: .././Pyblio/Fields.py:269
msgid "Illegal month value"
msgstr "Valore del mese non lecito"

#: .././Pyblio/Fields.py:273
msgid "Illegal day value"
msgstr "Valore del giorno non lecito"

#: .././Pyblio/Fields.py:438
msgid "in %s"
msgstr "in %s"

#: .././Pyblio/LyX.py:39
msgid "no input pipe `%s'"
msgstr "manca pipe `%s' di input"

#: .././Pyblio/LyX.py:45
msgid "no output pipe `%s'"
msgstr "manca pipe `%s' di output"

#: .././Pyblio/Open.py:97
msgid "method `%s' provides no opener"
msgstr "il metodo `%s' non fornisce un opener"

#: .././Pyblio/Open.py:105
msgid "File `%s' does not exist"
msgstr "Il file `%s' non esiste"

#: .././Pyblio/Open.py:116
msgid "don't know how to open `%s'"
msgstr "non so come aprire `%s'"

#: .././Pyblio/Open.py:143
msgid "method `%s' provides no iterator"
msgstr "il metodo `%s' non fornisce un iteratore"

#: .././Pyblio/Format/BibTeX.py:345
msgid "key `%s' is malformed"
msgstr "la chiave `%s' è malformata"

#: .././Pyblio/Format/BibTeX.py:366
msgid "%s:%d: key `%s' already defined"
msgstr "%s:%d: la chiave `%s' esiste già"

#: .././Pyblio/GnomeUI/Editor.py:38
msgid "Last Name, First Name"
msgstr "Cognome, Nome"

#: .././Pyblio/GnomeUI/Editor.py:39
msgid "Text"
msgstr "Testo"

#: .././Pyblio/GnomeUI/Editor.py:42
msgid "Reference"
msgstr "Riferimento"

#: .././Pyblio/GnomeUI/Editor.py:258
msgid "Day"
msgstr "Giorno"

#: .././Pyblio/GnomeUI/Editor.py:267
msgid "Month"
msgstr "Mese"

#: .././Pyblio/GnomeUI/Editor.py:276
msgid "Year"
msgstr "Anno"

#: .././Pyblio/GnomeUI/Editor.py:301
msgid "Invalid day field in date"
msgstr "Campo del giorno non valido nella data"

#: .././Pyblio/GnomeUI/Editor.py:309
msgid "Invalid month field in date"
msgstr "Campo del mese non valido nella data"

#: .././Pyblio/GnomeUI/Editor.py:317
msgid "Invalid year field in date"
msgstr "Campo dell'anno non valido nella data"

#: .././Pyblio/GnomeUI/Editor.py:426
msgid "Entry type"
msgstr "Tipo di voce"

#: .././Pyblio/GnomeUI/Config.py:482 .././Pyblio/GnomeUI/Editor.py:428
msgid "Key"
msgstr "Chiave"

#: .././Pyblio/GnomeUI/Editor.py:471
msgid "Create Field"
msgstr "Crea il campo"

#: .././Pyblio/GnomeUI/Editor.py:539 .././Pyblio/GnomeUI/Fields.py:191
msgid "Mandatory"
msgstr "Obbligatorio"

#: .././Pyblio/GnomeUI/Editor.py:539 .././Pyblio/GnomeUI/Fields.py:192
msgid "Optional"
msgstr "Facoltativo"

#: .././Pyblio/GnomeUI/Editor.py:539
msgid "Extra"
msgstr "Supplementare"

#: .././Pyblio/GnomeUI/Editor.py:601
msgid "Invalid key format"
msgstr "Formato della chiave non valido"

#: .././Pyblio/GnomeUI/Editor.py:609
msgid "Key `%s' already exists"
msgstr "La chiave `%s' esiste già"

#: .././Pyblio/GnomeUI/Editor.py:676
msgid "Error in native string parsing"
msgstr "Errore durante l'analisi nella stringa nativa"

#: .././Pyblio/GnomeUI/Editor.py:689
msgid "Edit entry"
msgstr "Modifica la voce"

#: .././Pyblio/GnomeUI/Editor.py:703
msgid "Native Editing"
msgstr "Editing nativo"

#: .././Pyblio/GnomeUI/Editor.py:756
msgid "Standard Editing"
msgstr "Editing standard"

#: .././Pyblio/GnomeUI/Document.py:195 .././Pyblio/GnomeUI/FileSelector.py:41
msgid "File"
msgstr "File"

#: .././Pyblio/GnomeUI/FileSelector.py:74
msgid "Bibliography type:"
msgstr "Tipo di bibliografia:"

#: .././Pyblio/GnomeUI/Index.py:68
msgid "Add..."
msgstr "Aggiunge..."

#: .././Pyblio/GnomeUI/Index.py:69
msgid "Edit..."
msgstr "Modifica..."

#: .././Pyblio/GnomeUI/Index.py:70 .././Pyblio/GnomeUI/Search.py:178
msgid "Delete"
msgstr "Cancella"

#: .././Pyblio/GnomeUI/Search.py:109
msgid "Search"
msgstr "Ricerca"

#: .././Pyblio/GnomeUI/Fields.py:225 .././Pyblio/GnomeUI/Search.py:133
msgid "Field"
msgstr "Campo"

#: .././Pyblio/GnomeUI/Search.py:134
msgid "Pattern"
msgstr "Modello"

#: .././Pyblio/GnomeUI/Search.py:151
msgid "Simple Search"
msgstr "Ricerca semplice"

#: .././Pyblio/GnomeUI/Search.py:155
msgid "Search command:"
msgstr "Comando di ricerca:"

#: .././Pyblio/GnomeUI/Search.py:161
msgid "Expert Search"
msgstr "Ricerca avanzata"

#: .././Pyblio/GnomeUI/Search.py:199
msgid "Full database"
msgstr "Database completo"

#: .././Pyblio/GnomeUI/Search.py:243
msgid "internal error during evaluation"
msgstr "errore interno durante la valutazione"

#: .././Pyblio/GnomeUI/Search.py:292
msgid ""
"while compiling %s\n"
"error: %s"
msgstr ""
"Durante la compilazione di `%s'\n"
"errore: %s"

#: .././Pyblio/GnomeUI/Sort.py:42
msgid "Select sort criterions"
msgstr "Seleziona i criteri di ordinamento"

#: .././Pyblio/GnomeUI/Sort.py:53
msgid "Sort direction"
msgstr "Direzione di ordinamento"

#: .././Pyblio/GnomeUI/Sort.py:53
msgid "Sort criterions"
msgstr "Criteri di ordinamento"

#: .././Pyblio/GnomeUI/Sort.py:66
msgid "[Entry Type]"
msgstr "[Tipo di voce]"

#: .././Pyblio/GnomeUI/Sort.py:67
msgid "[Key Value]"
msgstr "[Valore della chiave]"

#: .././Pyblio/GnomeUI/Sort.py:92
msgid "Reorder"
msgstr "Riordina"

#: .././Pyblio/GnomeUI/Sort.py:93
msgid "Groups the active fields on the top of the list"
msgstr "Raggruppa i campi attivi in cima alla lista"

#: .././Pyblio/GnomeUI/Sort.py:97
msgid "Unselect all"
msgstr "Deseleziona tutto"

#: .././Pyblio/GnomeUI/Sort.py:98
msgid "Removes all the sort criterions"
msgstr "Rimuove tutti i criteri di ordinamento"

#: .././Pyblio/GnomeUI/Utils.py:163
msgid ""
"The following errors occured:\n"
"\n"
msgstr ""
"Sono avvenuti i seguenti errori:\n"
"\n"

#: .././Pyblio/GnomeUI/Document.py:52
msgid "_New"
msgstr "_Nuovo"

#: .././Pyblio/GnomeUI/Document.py:54
msgid "_Merge with..."
msgstr "_Incorpora con..."

#: .././Pyblio/GnomeUI/Document.py:58
msgid "_Previous Documents"
msgstr "Documenti _precedenti"

#: .././Pyblio/GnomeUI/Document.py:65
msgid "About..."
msgstr "Informazioni su..."

#: .././Pyblio/GnomeUI/Document.py:66
msgid "Submit a Bug Report"
msgstr "Invia un Bug Report"

#: .././Pyblio/GnomeUI/Document.py:78
msgid "_Add..."
msgstr "_Aggiunge..."

#: .././Pyblio/GnomeUI/Document.py:79
msgid "_Edit..."
msgstr "_Modifica..."

#: .././Pyblio/GnomeUI/Document.py:80
msgid "_Delete"
msgstr "_Cancella"

#: .././Pyblio/GnomeUI/Document.py:83
msgid "S_ort..."
msgstr "_Ordina..."

#: .././Pyblio/GnomeUI/Document.py:87
msgid "_Cite"
msgstr "_Cita"

#: .././Pyblio/GnomeUI/Document.py:88
msgid "_Format..."
msgstr "_Formato..."

#: .././Pyblio/GnomeUI/Document.py:92
msgid "_Fields..."
msgstr "_Campi..."

#: .././Pyblio/GnomeUI/Document.py:93
msgid "_Entries..."
msgstr "_Voci..."

#: .././Pyblio/GnomeUI/Document.py:99
msgid "_File"
msgstr "_File"

#: .././Pyblio/GnomeUI/Document.py:100
msgid "_Edit"
msgstr "_Modifica"

#: .././Pyblio/GnomeUI/Document.py:102
msgid "_Settings"
msgstr "Impo_stazioni"

#: .././Pyblio/GnomeUI/Document.py:103
msgid "_Help"
msgstr "_Aiuto"

#: .././Pyblio/GnomeUI/Document.py:107
msgid "Open"
msgstr "Apri"

#: .././Pyblio/GnomeUI/Document.py:108
msgid "Save"
msgstr "Salva"

#: .././Pyblio/GnomeUI/Document.py:110
msgid "Find"
msgstr "Trova"

#: .././Pyblio/GnomeUI/Document.py:111
msgid "Cite"
msgstr "Cita"

#: .././Pyblio/GnomeUI/Document.py:113
msgid "Close"
msgstr "Chiudi"

#: .././Pyblio/GnomeUI/Document.py:195
msgid "Previous Documents"
msgstr "Documenti precedenti"

#: .././Pyblio/GnomeUI/Document.py:231
msgid ""
"can't open file `%s' for writing:\n"
"%s"
msgstr ""
"Impossibile aprire il file `%s' per la scrittura:\n"
"%s"

#: .././Pyblio/GnomeUI/Document.py:252
msgid ""
"Error while parsing `%s':\n"
"%s"
msgstr ""
"Errore durante l'analisi di `%s':\n"
"%s"

#: .././Pyblio/GnomeUI/Document.py:271
msgid "New database"
msgstr "Nuovo database"

#: .././Pyblio/GnomeUI/Document.py:279
msgid "[no entry]"
msgstr "[nessuna voce]"

#: .././Pyblio/GnomeUI/Document.py:280
msgid "[1 entry]"
msgstr "[1 voce]"

#: .././Pyblio/GnomeUI/Document.py:281
msgid "[%d entries]"
msgstr "[%d voci]"

#: .././Pyblio/GnomeUI/Document.py:284
msgid "[%d/1 entry]"
msgstr "[%d/1 voce]"

#: .././Pyblio/GnomeUI/Document.py:285
msgid "[%d/%d entries]"
msgstr "[%d/%d voci]"

#: .././Pyblio/GnomeUI/Document.py:290
msgid "[modified]"
msgstr "[modificato]"

#: .././Pyblio/GnomeUI/Document.py:300
msgid ""
"The database has been modified.\n"
"Discard changes ?"
msgstr ""
"Il database è stato modificato.\n"
"Scartare i cambiamenti?"

#: .././Pyblio/GnomeUI/Document.py:316
msgid "Merge file"
msgstr "Incorpora un file"

#: .././Pyblio/GnomeUI/Document.py:328
msgid "Open error"
msgstr "Errore di apertura"

#: .././Pyblio/GnomeUI/Document.py:352
msgid "Merge status"
msgstr "Stato di incorporamento"

#: .././Pyblio/GnomeUI/Document.py:363
msgid "Open file"
msgstr "Apri un file"

#: .././Pyblio/GnomeUI/Document.py:413
msgid ""
"The database has been externally modified.\n"
"Overwrite changes ?"
msgstr ""
"Il database è stato modificato dall'esterno.\n"
"Sovrascrivo i cambiamenti?"

#: .././Pyblio/GnomeUI/Document.py:423
msgid ""
"Unable to save `%s':\n"
"%s"
msgstr ""
"Impossibile salvare `%s':\n"
"%s"

#: .././Pyblio/GnomeUI/Document.py:431
msgid ""
"An internal error occured during saving\n"
"Try to Save As..."
msgstr ""
"E` avvenuto un errore interno durante il salvataggio\n"
"Provare  Salva con nome..."

#: .././Pyblio/GnomeUI/Document.py:445
msgid "Save As..."
msgstr "Salva con nome..."

#: .././Pyblio/GnomeUI/Document.py:451
msgid ""
"The file `%s' already exists.\n"
"Overwrite it ?"
msgstr ""
"Il file `%s' esiste già.\n"
"Sovrascriverlo ?"

#: .././Pyblio/GnomeUI/Document.py:458
msgid ""
"During opening:\n"
"%s"
msgstr ""
"Durante l'apertura:\n"
"%s"

#: .././Pyblio/GnomeUI/Document.py:478
msgid "Reopen error"
msgstr "Errore di riapertura"

#: .././Pyblio/GnomeUI/Document.py:519
msgid ""
"An entry called `%s' already exists.\n"
"Rename and add it anyway ?"
msgstr ""
"Una voce chiamata `%s' esiste già.\n"
"Rinominarla e aggiungerla comunque ?"

#: .././Pyblio/GnomeUI/Document.py:556
msgid "Really remove all the entries ?"
msgstr "Rimuovere veramente tutte le voci ?"

#: .././Pyblio/GnomeUI/Document.py:576
msgid "Create new entry"
msgstr "Crea una nuova voce"

#: .././Pyblio/GnomeUI/Document.py:590
msgid "Really edit %d entries ?"
msgstr "Modificare veramente le %d voci ?"

#: .././Pyblio/GnomeUI/Document.py:628
msgid "Remove all the %d entries ?"
msgstr "Rimuovere tutte le %d voci ?"

#: .././Pyblio/GnomeUI/Document.py:630
msgid "Remove entry `%s' ?"
msgstr "Rimuovere la voce `%s' ?"

#: .././Pyblio/GnomeUI/Document.py:696
msgid ""
"Can't connect to LyX:\n"
"%s"
msgstr ""
"Impossibile connettersi a LyX:\n"
"%s"

#: .././Pyblio/GnomeUI/Document.py:750
msgid ""
"Please install bug-buddy\n"
"to use this feature"
msgstr ""
"Per favore installare bug-buddy\n"
"per usare questa funzione"

#: .././Pyblio/GnomeUI/Document.py:761
msgid "This program is copyrighted under the GNU GPL"
msgstr "Questo programma è coperto dalla licenza GNU GPL"

#: .././Pyblio/GnomeUI/Document.py:763
msgid "Gnome interface to the Pybliographer system."
msgstr "Interfaccia Gnome a Pybliographer"

#: .././Pyblio/GnomeUI/Document.py:768
msgid "Pybliographer Home Page"
msgstr "Home Page di Pybliographer"

#: .././Pyblio/GnomeUI/Format.py:37
msgid "Format entries"
msgstr "Formato delle voci"

#: .././Pyblio/GnomeUI/Format.py:51
msgid "Bibliography style:"
msgstr "Stile di bibliografia:"

#: .././Pyblio/GnomeUI/Format.py:52
msgid "Select style"
msgstr "Selezionare lo stile"

#: .././Pyblio/GnomeUI/Format.py:58
msgid "Output format:"
msgstr "Formato di output:"

#: .././Pyblio/GnomeUI/Format.py:75
msgid "Output File:"
msgstr "File di output:"

#: .././Pyblio/GnomeUI/Format.py:76
msgid "Select output file"
msgstr "Selezionare il file di output"

#: .././Pyblio/GnomeUI/Config.py:45
msgid "Choose your preferences"
msgstr "Scegliere le vostre preferenze"

#: .././Pyblio/GnomeUI/Config.py:93
msgid ""
"Item `%s':\n"
"\n"
"%s"
msgstr ""
"Elemento `%s':\n"
"\n"
"%s"

#: .././Pyblio/GnomeUI/Config.py:128 .././Pyblio/GnomeUI/Fields.py:157
msgid ""
"Some changes require to restart Pybliographic\n"
"to be correctly taken into account"
msgstr ""
"Alcuni cambiamenti richiedono il riavvio di Pybliographic\n"
"per essere presi correttamente in considerazione"

#: .././Pyblio/GnomeUI/Config.py:249
msgid "True"
msgstr "Vero"

#: .././Pyblio/GnomeUI/Config.py:250
msgid "False"
msgstr "Falso"

#: .././Pyblio/GnomeUI/Config.py:390
msgid "Add"
msgstr "Aggiunge"

#: .././Pyblio/GnomeUI/Config.py:393
msgid "Update"
msgstr "Aggiorna"

#: .././Pyblio/GnomeUI/Config.py:396
msgid "Remove"
msgstr "Rimuove"

#: .././Pyblio/GnomeUI/Config.py:482
msgid "Value"
msgstr "Valore"

#: .././Pyblio/GnomeUI/Config.py:491 .././Pyblio/GnomeUI/Fields.py:93
msgid "Set"
msgstr "Imposta"

#: .././Pyblio/GnomeUI/Config.py:507
msgid "Key:"
msgstr "Chiave:"

#: .././Pyblio/GnomeUI/Config.py:509
msgid "Value:"
msgstr "Valore:"

#: .././Pyblio/GnomeUI/Fields.py:45
msgid "Fields configuration"
msgstr "Configurazione dei campi"

#: .././Pyblio/GnomeUI/Fields.py:59
msgid "Name"
msgstr "Nome"

#: .././Pyblio/GnomeUI/Fields.py:59
msgid "Type"
msgstr "Tipo"

#: .././Pyblio/GnomeUI/Fields.py:70
msgid "Name:"
msgstr "Nome:"

#: .././Pyblio/GnomeUI/Fields.py:72
msgid "Type:"
msgstr "Tipo:"

#: .././Pyblio/GnomeUI/Fields.py:198
msgid "Entries configuration"
msgstr "Configurazione delle voci"

#: .././Pyblio/GnomeUI/Fields.py:209
msgid "Entry"
msgstr "Voce"

#: .././Pyblio/GnomeUI/Fields.py:220
msgid "Entry Name:"
msgstr "Nome della voce:"

#: .././Pyblio/GnomeUI/Fields.py:225
msgid "Status"
msgstr "Stato"

#: .././pybliographer.py:48
msgid "This is %s, version %s"
msgstr "Questo è %s, versione %s"

#: .././pybliographer.py:52
msgid "This is free software with ABSOLUTELY NO WARRANTY."
msgstr "Questo è software libero SENZA NESSUNA GARANZIA."

#: .././pybliographer.py:53
msgid "For details, type `warranty'."
msgstr "Per i dettagli, digitare `warranty'."

#: .././pybliographer.py:116
msgid "%s: error: can't open file `%s'"
msgstr "%s: errore: impossibile aprire il file `%s'"

#: .././pybliographer.py:129
msgid "For help, run %s and type `help' at the prompt"
msgstr "Per l'aiuto, eseguire %s e digitare `help' al prompt"

#: .././pybliographer.py:138
msgid ""
"Useful commands:\n"
"\thelp     to get some help\n"
"\tquit     to quit\n"
msgstr ""
"Comandi utili:\n"
"\thelp     per ottenere aiuto\n"
"\tquit     per abbandonare\n"

#: .././scripts/pybcompact.py:30
msgid "usage: pybcompact <latexfile> <bibtexfiles...>"
msgstr "uso: pybcompact <latexfile> <bibtexfiles...>"

#: .././scripts/pybcompact.py:34
msgid "pybcompact: error: %s\n"
msgstr "pybcompact: errore: %s\n"

#: .././scripts/pybcompact.py:97
msgid "no entry"
msgstr "nessuna voce"

#: .././scripts/pybcompact.py:142
msgid "can't find the following entries: %s"
msgstr "impossibile trovare le seguenti voci: %s"

#: .././scripts/pybconvert.py:29
msgid "usage: pybconvert <source>..<target> <input> [output]"
msgstr "uso: pybconvert <source>..<target> <input> [output]"

#: .././scripts/pybconvert.py:38
msgid "pybconvert: bad conversion format"
msgstr "pybconvert: formato di conversione non valido"

#: .././scripts/pybformat.py:34
msgid "usage: pybformat [bibtexfiles...]\n"
msgstr "uso: pybformat [bibtexfiles...]\n"

#: .././scripts/pybformat.py:38
msgid "pybformat: error: %s\n"
msgstr "pybformat: errore: %s\n"

#: .././scripts/pybformat.py:44
msgid "pybformat: warning: %s\n"
msgstr "pybformat: attenzione: %s\n"

#: .././scripts/pybformat.py:141 .././scripts/pybtex.py:86
msgid "can't find style `%s'"
msgstr "impossibile trovare lo stile `%s'"

#: .././scripts/pybtex.py:34
msgid "usage: pybtex <latexfile> [bibtexfiles...]"
msgstr "uso: pybtex <latexfile> [bibtexfile...]"

#: .././scripts/pybtex.py:38
msgid "pybtex: error: %s\n"
msgstr "pybtex: errore: %s\n"

#: .././scripts/pybtex.py:59
msgid "pybtex: warning: the following keys were not resolved"
msgstr "pybtex: attenzione: le seguenti chiavi non sono risolte"

#: .././scripts/pybtex.py:64
msgid "no style defined"
msgstr "nessuno stile definito"
