# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Free Software Foundation, Inc.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2000-11-30 09:28+ZONE\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: ENCODING\n"

#: .././Pyblio/Autoload.py:57
msgid "warning: can't import %s: %s"
msgstr ""

#: .././Pyblio/Config.py:53
msgid "value of `%s' should be of type %s"
msgstr ""

#: .././Pyblio/Config.py:196
msgid "String"
msgstr ""

#: .././Pyblio/Config.py:205
msgid "Boolean"
msgstr ""

#: .././Pyblio/Config.py:224
msgid "Integer"
msgstr ""

#: .././Pyblio/Config.py:226
msgid "Integer under %d"
msgstr ""

#: .././Pyblio/Config.py:228
msgid "Integer over %d"
msgstr ""

#: .././Pyblio/Config.py:230
msgid "Integer between %d and %d"
msgstr ""

#: .././Pyblio/Config.py:242
msgid "Element in `%s'"
msgstr ""

#: .././Pyblio/Config.py:262
msgid "Tuple (%s)"
msgstr ""

#: .././Pyblio/Config.py:283
msgid "List (%s)"
msgstr ""

#: .././Pyblio/Config.py:308
msgid "Dictionary (%s, %s)"
msgstr ""

#: .././Pyblio/Fields.py:265
msgid "Illegal year value"
msgstr ""

#: .././Pyblio/Fields.py:269
msgid "Illegal month value"
msgstr ""

#: .././Pyblio/Fields.py:273
msgid "Illegal day value"
msgstr ""

#: .././Pyblio/Fields.py:438
msgid "in %s"
msgstr ""

#: .././Pyblio/LyX.py:39
msgid "no input pipe `%s'"
msgstr ""

#: .././Pyblio/LyX.py:45
msgid "no output pipe `%s'"
msgstr ""

#: .././Pyblio/Open.py:97
msgid "method `%s' provides no opener"
msgstr ""

#: .././Pyblio/Open.py:105 :151
msgid "File `%s' does not exist"
msgstr ""

#: .././Pyblio/Open.py:116 :162
msgid "don't know how to open `%s'"
msgstr ""

#: .././Pyblio/Open.py:143
msgid "method `%s' provides no iterator"
msgstr ""

#: .././Pyblio/Format/BibTeX.py:345 :403
msgid "key `%s' is malformed"
msgstr ""

#: .././Pyblio/Format/BibTeX.py:366 :387
msgid "%s:%d: key `%s' already defined"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:38
msgid "Last Name, First Name"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:39
msgid "Text"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:42
msgid "Reference"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:258
msgid "Day"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:267
msgid "Month"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:276
msgid "Year"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:301
msgid "Invalid day field in date"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:309
msgid "Invalid month field in date"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:317
msgid "Invalid year field in date"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:426
msgid "Entry type"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:428 .././Pyblio/GnomeUI/Config.py:482
msgid "Key"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:471
msgid "Create Field"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:539 .././Pyblio/GnomeUI/Fields.py:191
msgid "Mandatory"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:539 .././Pyblio/GnomeUI/Fields.py:192
msgid "Optional"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:539
msgid "Extra"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:601
msgid "Invalid key format"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:609
msgid "Key `%s' already exists"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:676
msgid "Error in native string parsing"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:689
msgid "Edit entry"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:703 :744
msgid "Native Editing"
msgstr ""

#: .././Pyblio/GnomeUI/Editor.py:756
msgid "Standard Editing"
msgstr ""

#: .././Pyblio/GnomeUI/FileSelector.py:41 .././Pyblio/GnomeUI/Document.py:195
#: :209
msgid "File"
msgstr ""

#: .././Pyblio/GnomeUI/FileSelector.py:74
msgid "Bibliography type:"
msgstr ""

#: .././Pyblio/GnomeUI/Index.py:68
msgid "Add..."
msgstr ""

#: .././Pyblio/GnomeUI/Index.py:69
msgid "Edit..."
msgstr ""

#: .././Pyblio/GnomeUI/Index.py:70 .././Pyblio/GnomeUI/Search.py:178
msgid "Delete"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:109
msgid "Search"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:133 .././Pyblio/GnomeUI/Fields.py:225
msgid "Field"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:134
msgid "Pattern"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:151
msgid "Simple Search"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:155
msgid "Search command:"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:161
msgid "Expert Search"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:199
msgid "Full database"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:243
msgid "internal error during evaluation"
msgstr ""

#: .././Pyblio/GnomeUI/Search.py:292
msgid ""
"while compiling %s\n"
"error: %s"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:42
msgid "Select sort criterions"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:53
msgid "Sort direction"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:53
msgid "Sort criterions"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:66
msgid "[Entry Type]"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:67
msgid "[Key Value]"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:92
msgid "Reorder"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:93
msgid "Groups the active fields on the top of the list"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:97
msgid "Unselect all"
msgstr ""

#: .././Pyblio/GnomeUI/Sort.py:98
msgid "Removes all the sort criterions"
msgstr ""

#: .././Pyblio/GnomeUI/Utils.py:163
msgid "The following errors occured:\n\n"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:52
msgid "_New"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:54
msgid "_Merge with..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:58
msgid "_Previous Documents"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:65
msgid "About..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:66
msgid "Submit a Bug Report"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:78
msgid "_Add..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:79
msgid "_Edit..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:80
msgid "_Delete"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:83
msgid "S_ort..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:87 :101
msgid "_Cite"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:88
msgid "_Format..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:92
msgid "_Fields..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:93
msgid "_Entries..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:99
msgid "_File"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:100
msgid "_Edit"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:102
msgid "_Settings"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:103
msgid "_Help"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:107
msgid "Open"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:108
msgid "Save"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:110
msgid "Find"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:111
msgid "Cite"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:113
msgid "Close"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:195 :209
msgid "Previous Documents"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:231
msgid ""
"can't open file `%s' for writing:\n"
"%s"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:252
msgid ""
"Error while parsing `%s':\n"
"%s"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:271
msgid "New database"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:279 :283
msgid "[no entry]"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:280
msgid "[1 entry]"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:281
msgid "[%d entries]"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:284
msgid "[%d/1 entry]"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:285
msgid "[%d/%d entries]"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:290
msgid "[modified]"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:300
msgid ""
"The database has been modified.\n"
"Discard changes ?"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:316
msgid "Merge file"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:328 :388
msgid "Open error"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:352
msgid "Merge status"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:363
msgid "Open file"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:413
msgid ""
"The database has been externally modified.\n"
"Overwrite changes ?"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:423
msgid ""
"Unable to save `%s':\n"
"%s"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:431
msgid ""
"An internal error occured during saving\n"
"Try to Save As..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:445
msgid "Save As..."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:451
msgid ""
"The file `%s' already exists.\n"
"Overwrite it ?"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:458
msgid ""
"During opening:\n"
"%s"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:478
msgid "Reopen error"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:519
msgid ""
"An entry called `%s' already exists.\n"
"Rename and add it anyway ?"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:556
msgid "Really remove all the entries ?"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:576
msgid "Create new entry"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:590
msgid "Really edit %d entries ?"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:628
msgid "Remove all the %d entries ?"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:630
msgid "Remove entry `%s' ?"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:696 :703
msgid ""
"Can't connect to LyX:\n"
"%s"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:750
msgid ""
"Please install bug-buddy\n"
"to use this feature"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:761
msgid "This program is copyrighted under the GNU GPL"
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:763
msgid "Gnome interface to the Pybliographer system."
msgstr ""

#: .././Pyblio/GnomeUI/Document.py:768
msgid "Pybliographer Home Page"
msgstr ""

#: .././Pyblio/GnomeUI/Format.py:37
msgid "Format entries"
msgstr ""

#: .././Pyblio/GnomeUI/Format.py:51
msgid "Bibliography style:"
msgstr ""

#: .././Pyblio/GnomeUI/Format.py:52
msgid "Select style"
msgstr ""

#: .././Pyblio/GnomeUI/Format.py:58
msgid "Output format:"
msgstr ""

#: .././Pyblio/GnomeUI/Format.py:75
msgid "Output File:"
msgstr ""

#: .././Pyblio/GnomeUI/Format.py:76
msgid "Select output file"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:45
msgid "Choose your preferences"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:93
msgid ""
"Item `%s':\n"
"\n"
"%s"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:128 .././Pyblio/GnomeUI/Fields.py:157 :339
msgid ""
"Some changes require to restart Pybliographic\n"
"to be correctly taken into account"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:249
msgid "True"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:250
msgid "False"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:390
msgid "Add"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:393
msgid "Update"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:396 :494 .././Pyblio/GnomeUI/Fields.py:96 :239
msgid "Remove"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:482
msgid "Value"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:491 .././Pyblio/GnomeUI/Fields.py:93 :236
msgid "Set"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:507
msgid "Key:"
msgstr ""

#: .././Pyblio/GnomeUI/Config.py:509
msgid "Value:"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:45
msgid "Fields configuration"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:59
msgid "Name"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:59
msgid "Type"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:70
msgid "Name:"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:72
msgid "Type:"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:198
msgid "Entries configuration"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:209
msgid "Entry"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:220
msgid "Entry Name:"
msgstr ""

#: .././Pyblio/GnomeUI/Fields.py:225
msgid "Status"
msgstr ""

#: .././pybliographer.py:48
msgid "This is %s, version %s"
msgstr ""

#: .././pybliographer.py:52 :59
msgid "This is free software with ABSOLUTELY NO WARRANTY."
msgstr ""

#: .././pybliographer.py:53
msgid "For details, type `warranty'."
msgstr ""

#: .././pybliographer.py:116 :168
msgid "%s: error: can't open file `%s'"
msgstr ""

#: .././pybliographer.py:129
msgid "For help, run %s and type `help' at the prompt"
msgstr ""

#: .././pybliographer.py:138
msgid ""
"Useful commands:\n"
"\thelp     to get some help\n"
"\tquit     to quit\n"
msgstr ""

#: .././scripts/pybcompact.py:30
msgid "usage: pybcompact <latexfile> <bibtexfiles...>"
msgstr ""

#: .././scripts/pybcompact.py:34
msgid "pybcompact: error: %s\n"
msgstr ""

#: .././scripts/pybcompact.py:97
msgid "no entry"
msgstr ""

#: .././scripts/pybcompact.py:142
msgid "can't find the following entries: %s"
msgstr ""

#: .././scripts/pybconvert.py:29
msgid "usage: pybconvert <source>..<target> <input> [output]"
msgstr ""

#: .././scripts/pybconvert.py:38
msgid "pybconvert: bad conversion format"
msgstr ""

#: .././scripts/pybformat.py:34
msgid "usage: pybformat [bibtexfiles...]\n"
msgstr ""

#: .././scripts/pybformat.py:38
msgid "pybformat: error: %s\n"
msgstr ""

#: .././scripts/pybformat.py:44
msgid "pybformat: warning: %s\n"
msgstr ""

#: .././scripts/pybformat.py:141 .././scripts/pybtex.py:86
msgid "can't find style `%s'"
msgstr ""

#: .././scripts/pybtex.py:34
msgid "usage: pybtex <latexfile> [bibtexfiles...]"
msgstr ""

#: .././scripts/pybtex.py:38
msgid "pybtex: error: %s\n"
msgstr ""

#: .././scripts/pybtex.py:59
msgid "pybtex: warning: the following keys were not resolved"
msgstr ""

#: .././scripts/pybtex.py:64
msgid "no style defined"
msgstr ""
